db:
  image: mysql
  command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
  container_name: app-db
  environment:
    MYSQL_ROOT_PASSWORD: user
    MYSQL_DATABASE: user
    MYSQL_USER: user
    MYSQL_PASSWORD: user
    TZ: "Asia/Tokyo"
web:
  build: .
  container_name: app-web
  ports:
    - "8080:80"
    - "1883:1883"
  links:
    - db:db
